print("--------Nilai ke 1 --------")
a=int(input("nilai harian:"))
input("uts:")
input("uas:")
print("--------Nilai ke 2 --------")
input("nilai harian:")
input("uts:")
input("uas:")
print("--------total nilai --------")
